version: "3"

services:

  db:
    image: mysql:8.0.33
    ports:
      - "9090:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABSE: trelloDB
      MYSQL_TCP_PORT: 3306
    restart: on-failure

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:mysql://db:3306/trelloDB?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
            "spring.datasource.password": "root"
          }'
    restart: on-failure
    depends_on:
      - db

  ui:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    restart: on-failure
    depends_on:
      - api